remote_theme: pages-themes/leap-day@v0.2.0
langs: [fr_FR]
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
plugins:
- jekyll-remote-theme
exclude:
- vendor
title: "Documentation Pluigin Téléinfo"
description: "Ceci est la documentation du plugin Téléinfo"
author: "Ticed35 puis Noyax"

